"""Parameterized SQL helpers for the Streamlit UI."""
from __future__ import annotations

from typing import Any

import pandas as pd
from sqlalchemy import Engine, text


# ---------------------------------------------------------- filter facets --
def list_journals(engine: Engine) -> list[str]:
    sql = text("SELECT name FROM journals ORDER BY name")
    with engine.connect() as c:
        return [r[0] for r in c.execute(sql)]


def year_bounds(engine: Engine) -> tuple[int, int]:
    sql = text("SELECT MIN(year), MAX(year) FROM articles WHERE year IS NOT NULL")
    with engine.connect() as c:
        lo, hi = c.execute(sql).one()
    return int(lo or 2000), int(hi or 2026)


# ----------------------------------------------------------------- search --
def search_articles(
    engine: Engine,
    keyword: str | None,
    year_from: int | None,
    year_to: int | None,
    journals: list[str] | None,
    limit: int = 200,
) -> pd.DataFrame:
    """Search articles with optional filters. Returns DataFrame of summary rows."""
    where: list[str] = []
    params: dict[str, Any] = {"limit": limit}

    if keyword:
        where.append("(a.title ILIKE :kw OR a.abstract ILIKE :kw)")
        params["kw"] = f"%{keyword}%"
    if year_from is not None:
        where.append("a.year >= :yf")
        params["yf"] = year_from
    if year_to is not None:
        where.append("a.year <= :yt")
        params["yt"] = year_to
    if journals:
        where.append("j.name = ANY(:journals)")
        params["journals"] = list(journals)

    where_sql = "WHERE " + " AND ".join(where) if where else ""
    sql = text(f"""
        SELECT
            a.pmid,
            a.title,
            a.year,
            j.name AS journal,
            (SELECT COUNT(*) FROM article_authors aa WHERE aa.article_id = a.pmid) AS n_authors,
            (SELECT COUNT(*) FROM article_mesh am WHERE am.article_id = a.pmid) AS n_mesh
        FROM articles a
        LEFT JOIN journals j ON a.journal_id = j.id
        {where_sql}
        ORDER BY a.year DESC NULLS LAST, a.pmid DESC
        LIMIT :limit
    """)
    return pd.read_sql(sql, engine, params=params)


# ----------------------------------------------------------------- detail --
def get_article_detail(engine: Engine, pmid: int) -> dict | None:
    sql = text("""
        SELECT a.pmid, a.title, a.abstract, a.year, j.name AS journal
        FROM articles a
        LEFT JOIN journals j ON a.journal_id = j.id
        WHERE a.pmid = :pmid
    """)
    authors_sql = text("""
        SELECT au.full_name
        FROM article_authors aa
        JOIN authors au ON au.id = aa.author_id
        WHERE aa.article_id = :pmid
        ORDER BY aa.position
    """)
    mesh_sql = text("""
        SELECT mt.term
        FROM article_mesh am
        JOIN mesh_terms mt ON mt.id = am.mesh_id
        WHERE am.article_id = :pmid
        ORDER BY mt.term
    """)
    with engine.connect() as c:
        row = c.execute(sql, {"pmid": pmid}).mappings().fetchone()
        if not row:
            return None
        authors = [r[0] for r in c.execute(authors_sql, {"pmid": pmid})]
        mesh = [r[0] for r in c.execute(mesh_sql, {"pmid": pmid})]
    return {**dict(row), "authors": authors, "mesh_terms": mesh}


# ---------------------------------------------------------- LLM Q&A path --
def run_readonly_query(engine: Engine, sql: str, statement_timeout_ms: int = 5000) -> pd.DataFrame:
    """Execute a SELECT generated by the LLM under the read-only role."""
    with engine.connect() as c:
        c.execute(text(f"SET LOCAL statement_timeout = {statement_timeout_ms}"))
        return pd.read_sql(text(sql), c)
